"""
Stock universe definition.
India: NIFTY 50 + NIFTY Next 50 (100 stocks)
USA:  Top 50 S&P 500 / NASDAQ 100 stocks
Total: ~150 stocks
"""

# ── NIFTY 50 ─────────────────────────────────────────────────────────────────
NIFTY_50: list[dict] = [
    {"ticker": "RELIANCE.NS",  "name": "Reliance Industries",        "sector": "Energy",        "index": "NIFTY50"},
    {"ticker": "TCS.NS",       "name": "Tata Consultancy Services",  "sector": "IT",            "index": "NIFTY50"},
    {"ticker": "HDFCBANK.NS",  "name": "HDFC Bank",                  "sector": "Banking",       "index": "NIFTY50"},
    {"ticker": "INFY.NS",      "name": "Infosys",                    "sector": "IT",            "index": "NIFTY50"},
    {"ticker": "ICICIBANK.NS", "name": "ICICI Bank",                 "sector": "Banking",       "index": "NIFTY50"},
    {"ticker": "HINDUNILVR.NS","name": "Hindustan Unilever",         "sector": "FMCG",          "index": "NIFTY50"},
    {"ticker": "SBIN.NS",      "name": "State Bank of India",        "sector": "Banking",       "index": "NIFTY50"},
    {"ticker": "BHARTIARTL.NS","name": "Bharti Airtel",              "sector": "Telecom",       "index": "NIFTY50"},
    {"ticker": "ITC.NS",       "name": "ITC Limited",                "sector": "FMCG",          "index": "NIFTY50"},
    {"ticker": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank",        "sector": "Banking",       "index": "NIFTY50"},
    {"ticker": "LT.NS",        "name": "Larsen & Toubro",            "sector": "Infrastructure","index": "NIFTY50"},
    {"ticker": "HCLTECH.NS",   "name": "HCL Technologies",           "sector": "IT",            "index": "NIFTY50"},
    {"ticker": "AXISBANK.NS",  "name": "Axis Bank",                  "sector": "Banking",       "index": "NIFTY50"},
    {"ticker": "ASIANPAINT.NS","name": "Asian Paints",               "sector": "Materials",     "index": "NIFTY50"},
    {"ticker": "BAJFINANCE.NS","name": "Bajaj Finance",              "sector": "Finance",       "index": "NIFTY50"},
    {"ticker": "MARUTI.NS",    "name": "Maruti Suzuki",              "sector": "Auto",          "index": "NIFTY50"},
    {"ticker": "SUNPHARMA.NS", "name": "Sun Pharmaceutical",         "sector": "Pharma",        "index": "NIFTY50"},
    {"ticker": "TITAN.NS",     "name": "Titan Company",              "sector": "Consumer",      "index": "NIFTY50"},
    {"ticker": "WIPRO.NS",     "name": "Wipro",                      "sector": "IT",            "index": "NIFTY50"},
    {"ticker": "ULTRACEMCO.NS","name": "UltraTech Cement",           "sector": "Materials",     "index": "NIFTY50"},
    {"ticker": "NESTLEIND.NS", "name": "Nestle India",               "sector": "FMCG",          "index": "NIFTY50"},
    {"ticker": "POWERGRID.NS", "name": "Power Grid Corporation",     "sector": "Utilities",     "index": "NIFTY50"},
    {"ticker": "NTPC.NS",      "name": "NTPC Limited",               "sector": "Utilities",     "index": "NIFTY50"},
    {"ticker": "TECHM.NS",     "name": "Tech Mahindra",              "sector": "IT",            "index": "NIFTY50"},
    {"ticker": "ONGC.NS",      "name": "ONGC",                       "sector": "Energy",        "index": "NIFTY50"},
    {"ticker": "TATAMOTORS.NS","name": "Tata Motors",                "sector": "Auto",          "index": "NIFTY50"},
    {"ticker": "ADANIENT.NS",  "name": "Adani Enterprises",          "sector": "Conglomerate",  "index": "NIFTY50"},
    {"ticker": "JSWSTEEL.NS",  "name": "JSW Steel",                  "sector": "Metals",        "index": "NIFTY50"},
    {"ticker": "TATASTEEL.NS", "name": "Tata Steel",                 "sector": "Metals",        "index": "NIFTY50"},
    {"ticker": "COALINDIA.NS", "name": "Coal India",                 "sector": "Energy",        "index": "NIFTY50"},
    {"ticker": "BAJAJFINSV.NS","name": "Bajaj Finserv",              "sector": "Finance",       "index": "NIFTY50"},
    {"ticker": "HDFCLIFE.NS",  "name": "HDFC Life Insurance",        "sector": "Insurance",     "index": "NIFTY50"},
    {"ticker": "SBILIFE.NS",   "name": "SBI Life Insurance",         "sector": "Insurance",     "index": "NIFTY50"},
    {"ticker": "INDUSINDBK.NS","name": "IndusInd Bank",              "sector": "Banking",       "index": "NIFTY50"},
    {"ticker": "GRASIM.NS",    "name": "Grasim Industries",          "sector": "Materials",     "index": "NIFTY50"},
    {"ticker": "DRREDDY.NS",   "name": "Dr. Reddy's Laboratories",   "sector": "Pharma",        "index": "NIFTY50"},
    {"ticker": "CIPLA.NS",     "name": "Cipla",                      "sector": "Pharma",        "index": "NIFTY50"},
    {"ticker": "EICHERMOT.NS", "name": "Eicher Motors",              "sector": "Auto",          "index": "NIFTY50"},
    {"ticker": "HEROMOTOCO.NS","name": "Hero MotoCorp",              "sector": "Auto",          "index": "NIFTY50"},
    {"ticker": "APOLLOHOSP.NS","name": "Apollo Hospitals",           "sector": "Healthcare",    "index": "NIFTY50"},
    {"ticker": "TATACONSUM.NS","name": "Tata Consumer Products",     "sector": "FMCG",          "index": "NIFTY50"},
    {"ticker": "DIVISLAB.NS",  "name": "Divi's Laboratories",        "sector": "Pharma",        "index": "NIFTY50"},
    {"ticker": "BPCL.NS",      "name": "Bharat Petroleum",          "sector": "Energy",        "index": "NIFTY50"},
    {"ticker": "SHREECEM.NS",  "name": "Shree Cement",               "sector": "Materials",     "index": "NIFTY50"},
    {"ticker": "ADANIPORTS.NS","name": "Adani Ports",                "sector": "Infrastructure","index": "NIFTY50"},
    {"ticker": "M&M.NS",       "name": "Mahindra & Mahindra",        "sector": "Auto",          "index": "NIFTY50"},
    {"ticker": "BRITANNIA.NS", "name": "Britannia Industries",       "sector": "FMCG",          "index": "NIFTY50"},
    {"ticker": "BAJAJ-AUTO.NS","name": "Bajaj Auto",                 "sector": "Auto",          "index": "NIFTY50"},
    {"ticker": "UPL.NS",       "name": "UPL Limited",                "sector": "Chemicals",     "index": "NIFTY50"},
    {"ticker": "HINDALCO.NS",  "name": "Hindalco Industries",        "sector": "Metals",        "index": "NIFTY50"},
]

# ── NIFTY Next 50 ─────────────────────────────────────────────────────────────
NIFTY_NEXT_50: list[dict] = [
    {"ticker": "ABB.NS",        "name": "ABB India",                 "sector": "Industrials",   "index": "NIFTY_NEXT50"},
    {"ticker": "ADANIGREEN.NS", "name": "Adani Green Energy",        "sector": "Utilities",     "index": "NIFTY_NEXT50"},
    {"ticker": "ADANITRANS.NS", "name": "Adani Transmission",        "sector": "Utilities",     "index": "NIFTY_NEXT50"},
    {"ticker": "AMBUJACEM.NS",  "name": "Ambuja Cements",            "sector": "Materials",     "index": "NIFTY_NEXT50"},
    {"ticker": "AUROPHARMA.NS", "name": "Aurobindo Pharma",          "sector": "Pharma",        "index": "NIFTY_NEXT50"},
    {"ticker": "BANDHANBNK.NS", "name": "Bandhan Bank",              "sector": "Banking",       "index": "NIFTY_NEXT50"},
    {"ticker": "BANKBARODA.NS", "name": "Bank of Baroda",            "sector": "Banking",       "index": "NIFTY_NEXT50"},
    {"ticker": "BERGEPAINT.NS", "name": "Berger Paints",             "sector": "Materials",     "index": "NIFTY_NEXT50"},
    {"ticker": "BOSCHLTD.NS",   "name": "Bosch",                     "sector": "Auto",          "index": "NIFTY_NEXT50"},
    {"ticker": "CHOLAFIN.NS",   "name": "Cholamandalam Finance",     "sector": "Finance",       "index": "NIFTY_NEXT50"},
    {"ticker": "COLPAL.NS",     "name": "Colgate-Palmolive India",   "sector": "FMCG",          "index": "NIFTY_NEXT50"},
    {"ticker": "CUMMINSIND.NS", "name": "Cummins India",             "sector": "Industrials",   "index": "NIFTY_NEXT50"},
    {"ticker": "DABUR.NS",      "name": "Dabur India",               "sector": "FMCG",          "index": "NIFTY_NEXT50"},
    {"ticker": "DLF.NS",        "name": "DLF Limited",               "sector": "Real Estate",   "index": "NIFTY_NEXT50"},
    {"ticker": "FEDERALBNK.NS", "name": "Federal Bank",              "sector": "Banking",       "index": "NIFTY_NEXT50"},
    {"ticker": "GODREJCP.NS",   "name": "Godrej Consumer Products",  "sector": "FMCG",          "index": "NIFTY_NEXT50"},
    {"ticker": "HAVELLS.NS",    "name": "Havells India",             "sector": "Consumer",      "index": "NIFTY_NEXT50"},
    {"ticker": "HDFCAMC.NS",    "name": "HDFC AMC",                  "sector": "Finance",       "index": "NIFTY_NEXT50"},
    {"ticker": "HINDPETRO.NS",  "name": "Hindustan Petroleum (HPCL)","sector": "Energy",        "index": "NIFTY_NEXT50"},
    {"ticker": "ICICIGI.NS",    "name": "ICICI Lombard",             "sector": "Insurance",     "index": "NIFTY_NEXT50"},
    {"ticker": "ICICIPRULI.NS", "name": "ICICI Prudential Life",     "sector": "Insurance",     "index": "NIFTY_NEXT50"},
    {"ticker": "IDFCFIRSTB.NS", "name": "IDFC First Bank",           "sector": "Banking",       "index": "NIFTY_NEXT50"},
    {"ticker": "IGL.NS",        "name": "Indraprastha Gas",          "sector": "Utilities",     "index": "NIFTY_NEXT50"},
    {"ticker": "INDUSTOWER.NS", "name": "Indus Towers",              "sector": "Telecom",       "index": "NIFTY_NEXT50"},
    {"ticker": "LTIM.NS",       "name": "LTIMindtree",               "sector": "IT",            "index": "NIFTY_NEXT50"},
    {"ticker": "LTTS.NS",       "name": "L&T Technology Services",   "sector": "IT",            "index": "NIFTY_NEXT50"},
    {"ticker": "LUPIN.NS",      "name": "Lupin",                     "sector": "Pharma",        "index": "NIFTY_NEXT50"},
    {"ticker": "MARICO.NS",     "name": "Marico",                    "sector": "FMCG",          "index": "NIFTY_NEXT50"},
    {"ticker": "MCDOWELL-N.NS", "name": "United Spirits",            "sector": "Consumer",      "index": "NIFTY_NEXT50"},
    {"ticker": "MPHASIS.NS",    "name": "Mphasis",                   "sector": "IT",            "index": "NIFTY_NEXT50"},
    {"ticker": "MUTHOOTFIN.NS", "name": "Muthoot Finance",           "sector": "Finance",       "index": "NIFTY_NEXT50"},
    {"ticker": "NAUKRI.NS",     "name": "Info Edge (Naukri)",        "sector": "IT",            "index": "NIFTY_NEXT50"},
    {"ticker": "OBEROIRLTY.NS", "name": "Oberoi Realty",             "sector": "Real Estate",   "index": "NIFTY_NEXT50"},
    {"ticker": "OFSS.NS",       "name": "Oracle Financial Services", "sector": "IT",            "index": "NIFTY_NEXT50"},
    {"ticker": "PAGEIND.NS",    "name": "Page Industries",           "sector": "Consumer",      "index": "NIFTY_NEXT50"},
    {"ticker": "PERSISTENT.NS", "name": "Persistent Systems",        "sector": "IT",            "index": "NIFTY_NEXT50"},
    {"ticker": "PETRONET.NS",   "name": "Petronet LNG",              "sector": "Energy",        "index": "NIFTY_NEXT50"},
    {"ticker": "PIDILITIND.NS", "name": "Pidilite Industries",       "sector": "Chemicals",     "index": "NIFTY_NEXT50"},
    {"ticker": "PIIND.NS",      "name": "PI Industries",             "sector": "Chemicals",     "index": "NIFTY_NEXT50"},
    {"ticker": "PNBHOUSING.NS", "name": "PNB Housing Finance",       "sector": "Finance",       "index": "NIFTY_NEXT50"},
    {"ticker": "RECLTD.NS",     "name": "REC Limited",               "sector": "Finance",       "index": "NIFTY_NEXT50"},
    {"ticker": "SIEMENS.NS",    "name": "Siemens India",             "sector": "Industrials",   "index": "NIFTY_NEXT50"},
    {"ticker": "SRF.NS",        "name": "SRF Limited",               "sector": "Chemicals",     "index": "NIFTY_NEXT50"},
    {"ticker": "TATAPOWER.NS",  "name": "Tata Power",                "sector": "Utilities",     "index": "NIFTY_NEXT50"},
    {"ticker": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals",   "sector": "Pharma",        "index": "NIFTY_NEXT50"},
    {"ticker": "TRENT.NS",      "name": "Trent (Westside)",          "sector": "Retail",        "index": "NIFTY_NEXT50"},
    {"ticker": "VEDL.NS",       "name": "Vedanta",                   "sector": "Metals",        "index": "NIFTY_NEXT50"},
    {"ticker": "VOLTAS.NS",     "name": "Voltas",                    "sector": "Consumer",      "index": "NIFTY_NEXT50"},
    {"ticker": "ZYDUSLIFE.NS",  "name": "Zydus Lifesciences",        "sector": "Pharma",        "index": "NIFTY_NEXT50"},
    {"ticker": "POLYCAB.NS",    "name": "Polycab India",             "sector": "Industrials",   "index": "NIFTY_NEXT50"},
]

# ── US Top 50 (S&P 500 / NASDAQ 100) ─────────────────────────────────────────
US_TOP_50: list[dict] = [
    {"ticker": "AAPL",   "name": "Apple",                    "sector": "Technology",      "index": "SP500"},
    {"ticker": "MSFT",   "name": "Microsoft",                "sector": "Technology",      "index": "SP500"},
    {"ticker": "NVDA",   "name": "NVIDIA",                   "sector": "Technology",      "index": "SP500"},
    {"ticker": "GOOGL",  "name": "Alphabet (Google)",        "sector": "Communication",   "index": "SP500"},
    {"ticker": "AMZN",   "name": "Amazon",                   "sector": "Consumer Disc.",  "index": "SP500"},
    {"ticker": "META",   "name": "Meta Platforms",           "sector": "Communication",   "index": "SP500"},
    {"ticker": "TSLA",   "name": "Tesla",                    "sector": "Auto",            "index": "SP500"},
    {"ticker": "BRK-B",  "name": "Berkshire Hathaway B",     "sector": "Finance",         "index": "SP500"},
    {"ticker": "JPM",    "name": "JPMorgan Chase",           "sector": "Banking",         "index": "SP500"},
    {"ticker": "LLY",    "name": "Eli Lilly",                "sector": "Pharma",          "index": "SP500"},
    {"ticker": "V",      "name": "Visa",                     "sector": "Finance",         "index": "SP500"},
    {"ticker": "UNH",    "name": "UnitedHealth Group",       "sector": "Healthcare",      "index": "SP500"},
    {"ticker": "XOM",    "name": "ExxonMobil",               "sector": "Energy",          "index": "SP500"},
    {"ticker": "MA",     "name": "Mastercard",               "sector": "Finance",         "index": "SP500"},
    {"ticker": "AVGO",   "name": "Broadcom",                 "sector": "Technology",      "index": "SP500"},
    {"ticker": "PG",     "name": "Procter & Gamble",         "sector": "FMCG",            "index": "SP500"},
    {"ticker": "JNJ",    "name": "Johnson & Johnson",        "sector": "Healthcare",      "index": "SP500"},
    {"ticker": "COST",   "name": "Costco",                   "sector": "Retail",          "index": "SP500"},
    {"ticker": "HD",     "name": "Home Depot",               "sector": "Retail",          "index": "SP500"},
    {"ticker": "MRK",    "name": "Merck",                    "sector": "Pharma",          "index": "SP500"},
    {"ticker": "ABBV",   "name": "AbbVie",                   "sector": "Pharma",          "index": "SP500"},
    {"ticker": "BAC",    "name": "Bank of America",          "sector": "Banking",         "index": "SP500"},
    {"ticker": "CRM",    "name": "Salesforce",               "sector": "Technology",      "index": "SP500"},
    {"ticker": "AMD",    "name": "Advanced Micro Devices",   "sector": "Technology",      "index": "SP500"},
    {"ticker": "ORCL",   "name": "Oracle",                   "sector": "Technology",      "index": "SP500"},
    {"ticker": "CVX",    "name": "Chevron",                  "sector": "Energy",          "index": "SP500"},
    {"ticker": "PEP",    "name": "PepsiCo",                  "sector": "FMCG",            "index": "SP500"},
    {"ticker": "KO",     "name": "Coca-Cola",                "sector": "FMCG",            "index": "SP500"},
    {"ticker": "ADBE",   "name": "Adobe",                    "sector": "Technology",      "index": "SP500"},
    {"ticker": "TMO",    "name": "Thermo Fisher Scientific", "sector": "Healthcare",      "index": "SP500"},
    {"ticker": "WMT",    "name": "Walmart",                  "sector": "Retail",          "index": "SP500"},
    {"ticker": "MCD",    "name": "McDonald's",               "sector": "Consumer",        "index": "SP500"},
    {"ticker": "ACN",    "name": "Accenture",                "sector": "Technology",      "index": "SP500"},
    {"ticker": "NFLX",   "name": "Netflix",                  "sector": "Communication",   "index": "NASDAQ100"},
    {"ticker": "QCOM",   "name": "Qualcomm",                 "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "TXN",    "name": "Texas Instruments",        "sector": "Technology",      "index": "SP500"},
    {"ticker": "INTC",   "name": "Intel",                    "sector": "Technology",      "index": "SP500"},
    {"ticker": "GS",     "name": "Goldman Sachs",            "sector": "Banking",         "index": "SP500"},
    {"ticker": "NEE",    "name": "NextEra Energy",           "sector": "Utilities",       "index": "SP500"},
    {"ticker": "PM",     "name": "Philip Morris",            "sector": "Consumer",        "index": "SP500"},
    {"ticker": "IBM",    "name": "IBM",                      "sector": "Technology",      "index": "SP500"},
    {"ticker": "NOW",    "name": "ServiceNow",               "sector": "Technology",      "index": "SP500"},
    {"ticker": "UBER",   "name": "Uber Technologies",        "sector": "Technology",      "index": "SP500"},
    {"ticker": "AMGN",   "name": "Amgen",                    "sector": "Pharma",          "index": "NASDAQ100"},
    {"ticker": "CAT",    "name": "Caterpillar",              "sector": "Industrials",     "index": "SP500"},
    {"ticker": "GE",     "name": "GE Aerospace",             "sector": "Industrials",     "index": "SP500"},
    {"ticker": "RTX",    "name": "RTX Corporation",          "sector": "Defense",         "index": "SP500"},
    {"ticker": "SPGI",   "name": "S&P Global",               "sector": "Finance",         "index": "SP500"},
    {"ticker": "MS",     "name": "Morgan Stanley",           "sector": "Banking",         "index": "SP500"},
    {"ticker": "ISRG",   "name": "Intuitive Surgical",       "sector": "Healthcare",      "index": "SP500"},
]

# ── NIFTY Midcap & popular additional Indian stocks ───────────────────────────
INDIA_EXTRA: list[dict] = [
    {"ticker": "ZOMATO.NS",     "name": "Zomato",                    "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "PAYTM.NS",      "name": "One97 Communications (Paytm)", "sector": "Finance",    "index": "NIFTY_MIDCAP"},
    {"ticker": "NYKAA.NS",      "name": "FSN E-Commerce (Nykaa)",    "sector": "Retail",        "index": "NIFTY_MIDCAP"},
    {"ticker": "IRCTC.NS",      "name": "Indian Railway Catering",   "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "DMART.NS",      "name": "Avenue Supermarts (DMart)", "sector": "Retail",        "index": "NIFTY_MIDCAP"},
    {"ticker": "POLICYBZR.NS",  "name": "PB Fintech (PolicyBazaar)", "sector": "Finance",       "index": "NIFTY_MIDCAP"},
    {"ticker": "DELTACORP.NS",  "name": "Delta Corp",                "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "BEL.NS",        "name": "Bharat Electronics",        "sector": "Defense",       "index": "NIFTY_MIDCAP"},
    {"ticker": "HAL.NS",        "name": "Hindustan Aeronautics",     "sector": "Defense",       "index": "NIFTY_MIDCAP"},
    {"ticker": "BHEL.NS",       "name": "Bharat Heavy Electricals",  "sector": "Industrials",   "index": "NIFTY_MIDCAP"},
    {"ticker": "SAIL.NS",       "name": "Steel Authority of India",  "sector": "Metals",        "index": "NIFTY_MIDCAP"},
    {"ticker": "PFC.NS",        "name": "Power Finance Corporation", "sector": "Finance",       "index": "NIFTY_MIDCAP"},
    {"ticker": "RECLTD.NS",     "name": "REC Limited",               "sector": "Finance",       "index": "NIFTY_MIDCAP"},
    {"ticker": "IRFC.NS",       "name": "Indian Railway Finance Corp","sector": "Finance",      "index": "NIFTY_MIDCAP"},
    {"ticker": "RVNL.NS",       "name": "Rail Vikas Nigam",          "sector": "Infrastructure","index": "NIFTY_MIDCAP"},
    {"ticker": "SUZLON.NS",     "name": "Suzlon Energy",             "sector": "Utilities",     "index": "NIFTY_MIDCAP"},
    {"ticker": "YESBANK.NS",    "name": "Yes Bank",                  "sector": "Banking",       "index": "NIFTY_MIDCAP"},
    {"ticker": "PNB.NS",        "name": "Punjab National Bank",      "sector": "Banking",       "index": "NIFTY_MIDCAP"},
    {"ticker": "CANBK.NS",      "name": "Canara Bank",               "sector": "Banking",       "index": "NIFTY_MIDCAP"},
    {"ticker": "UNIONBANK.NS",  "name": "Union Bank of India",       "sector": "Banking",       "index": "NIFTY_MIDCAP"},
    {"ticker": "IOB.NS",        "name": "Indian Overseas Bank",      "sector": "Banking",       "index": "NIFTY_MIDCAP"},
    {"ticker": "Dixon.NS",      "name": "Dixon Technologies",        "sector": "Technology",    "index": "NIFTY_MIDCAP"},
    {"ticker": "TATAELXSI.NS",  "name": "Tata Elxsi",               "sector": "IT",            "index": "NIFTY_MIDCAP"},
    {"ticker": "KPITTECH.NS",   "name": "KPIT Technologies",         "sector": "IT",            "index": "NIFTY_MIDCAP"},
    {"ticker": "COFORGE.NS",    "name": "Coforge",                   "sector": "IT",            "index": "NIFTY_MIDCAP"},
    {"ticker": "TANLA.NS",      "name": "Tanla Platforms",           "sector": "IT",            "index": "NIFTY_MIDCAP"},
    {"ticker": "APLAPOLLO.NS",  "name": "APL Apollo Tubes",          "sector": "Metals",        "index": "NIFTY_MIDCAP"},
    {"ticker": "POLYCAB.NS",    "name": "Polycab India",             "sector": "Industrials",   "index": "NIFTY_MIDCAP"},
    {"ticker": "ASTRAL.NS",     "name": "Astral",                    "sector": "Materials",     "index": "NIFTY_MIDCAP"},
    {"ticker": "SUPREMEIND.NS", "name": "Supreme Industries",        "sector": "Materials",     "index": "NIFTY_MIDCAP"},
    {"ticker": "CROMPTON.NS",   "name": "Crompton Greaves Consumer", "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "WHIRLPOOL.NS",  "name": "Whirlpool of India",        "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "BATAINDIA.NS",  "name": "Bata India",                "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "VMART.NS",      "name": "V-Mart Retail",             "sector": "Retail",        "index": "NIFTY_MIDCAP"},
    {"ticker": "JUBLFOOD.NS",   "name": "Jubilant FoodWorks",        "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "DEVYANI.NS",    "name": "Devyani International",     "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "SAPPHIRE.NS",   "name": "Sapphire Foods",            "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "INDIAMART.NS",  "name": "IndiaMART InterMESH",       "sector": "IT",            "index": "NIFTY_MIDCAP"},
    {"ticker": "JUSTDIAL.NS",   "name": "Just Dial",                 "sector": "IT",            "index": "NIFTY_MIDCAP"},
    {"ticker": "INDIGOPNTS.NS", "name": "Indigo Paints",             "sector": "Materials",     "index": "NIFTY_MIDCAP"},
    {"ticker": "MAXHEALTH.NS",  "name": "Max Healthcare",            "sector": "Healthcare",    "index": "NIFTY_MIDCAP"},
    {"ticker": "FORTIS.NS",     "name": "Fortis Healthcare",         "sector": "Healthcare",    "index": "NIFTY_MIDCAP"},
    {"ticker": "STAR.NS",       "name": "Star Health Insurance",     "sector": "Insurance",     "index": "NIFTY_MIDCAP"},
    {"ticker": "NIACL.NS",      "name": "New India Assurance",       "sector": "Insurance",     "index": "NIFTY_MIDCAP"},
    {"ticker": "GICRE.NS",      "name": "GIC Re",                    "sector": "Insurance",     "index": "NIFTY_MIDCAP"},
    {"ticker": "TATACHEM.NS",   "name": "Tata Chemicals",            "sector": "Chemicals",     "index": "NIFTY_MIDCAP"},
    {"ticker": "AARTIIND.NS",   "name": "Aarti Industries",          "sector": "Chemicals",     "index": "NIFTY_MIDCAP"},
    {"ticker": "DEEPAKNI.NS",   "name": "Deepak Nitrite",            "sector": "Chemicals",     "index": "NIFTY_MIDCAP"},
    {"ticker": "CLEAN.NS",      "name": "Clean Science and Technology","sector": "Chemicals",   "index": "NIFTY_MIDCAP"},
    {"ticker": "IGPL.NS",       "name": "IG Petrochemicals",         "sector": "Chemicals",     "index": "NIFTY_MIDCAP"},
    {"ticker": "NHPC.NS",       "name": "NHPC",                      "sector": "Utilities",     "index": "NIFTY_MIDCAP"},
    {"ticker": "SJVN.NS",       "name": "SJVN",                      "sector": "Utilities",     "index": "NIFTY_MIDCAP"},
    {"ticker": "TORNTPOWER.NS", "name": "Torrent Power",             "sector": "Utilities",     "index": "NIFTY_MIDCAP"},
    {"ticker": "CESC.NS",       "name": "CESC",                      "sector": "Utilities",     "index": "NIFTY_MIDCAP"},
    {"ticker": "MRPL.NS",       "name": "Mangalore Refinery",        "sector": "Energy",        "index": "NIFTY_MIDCAP"},
    {"ticker": "HPCL.NS",       "name": "Hindustan Petroleum Corp",  "sector": "Energy",        "index": "NIFTY_MIDCAP"},
    {"ticker": "IOC.NS",        "name": "Indian Oil Corporation",    "sector": "Energy",        "index": "NIFTY_MIDCAP"},
    {"ticker": "GAIL.NS",       "name": "GAIL (India)",              "sector": "Energy",        "index": "NIFTY_MIDCAP"},
    {"ticker": "CONCOR.NS",     "name": "Container Corporation",     "sector": "Infrastructure","index": "NIFTY_MIDCAP"},
    {"ticker": "IRCON.NS",      "name": "Ircon International",       "sector": "Infrastructure","index": "NIFTY_MIDCAP"},
    {"ticker": "KIOCL.NS",      "name": "KIOCL",                     "sector": "Metals",        "index": "NIFTY_MIDCAP"},
    {"ticker": "NMDC.NS",       "name": "NMDC",                      "sector": "Metals",        "index": "NIFTY_MIDCAP"},
    {"ticker": "NATIONALUM.NS", "name": "National Aluminium",        "sector": "Metals",        "index": "NIFTY_MIDCAP"},
    {"ticker": "KALYANKJIL.NS", "name": "Kalyan Jewellers",          "sector": "Retail",        "index": "NIFTY_MIDCAP"},
    {"ticker": "SENCO.NS",      "name": "Senco Gold",                "sector": "Retail",        "index": "NIFTY_MIDCAP"},
    {"ticker": "SULA.NS",       "name": "Sula Vineyards",            "sector": "Consumer",      "index": "NIFTY_MIDCAP"},
    {"ticker": "UNOMINDA.NS",   "name": "Uno Minda",                 "sector": "Auto",          "index": "NIFTY_MIDCAP"},
    {"ticker": "MOTHERSON.NS",  "name": "Samvardhana Motherson",     "sector": "Auto",          "index": "NIFTY_MIDCAP"},
    {"ticker": "BALKRISIND.NS", "name": "Balkrishna Industries",     "sector": "Auto",          "index": "NIFTY_MIDCAP"},
    {"ticker": "EXIDEIND.NS",   "name": "Exide Industries",          "sector": "Auto",          "index": "NIFTY_MIDCAP"},
    {"ticker": "AMARAJABAT.NS", "name": "Amara Raja Energy",         "sector": "Auto",          "index": "NIFTY_MIDCAP"},
    {"ticker": "CARERATING.NS", "name": "CARE Ratings",              "sector": "Finance",       "index": "NIFTY_MIDCAP"},
    {"ticker": "CRISIL.NS",     "name": "CRISIL",                    "sector": "Finance",       "index": "NIFTY_MIDCAP"},
]

# ── Additional US stocks (S&P 500 / NASDAQ key names) ─────────────────────────
US_EXTRA: list[dict] = [
    {"ticker": "SPOT",   "name": "Spotify Technology",         "sector": "Communication",   "index": "NASDAQ100"},
    {"ticker": "PYPL",   "name": "PayPal Holdings",            "sector": "Finance",         "index": "SP500"},
    {"ticker": "SQ",     "name": "Block (Square)",             "sector": "Finance",         "index": "SP500"},
    {"ticker": "COIN",   "name": "Coinbase Global",            "sector": "Finance",         "index": "NASDAQ100"},
    {"ticker": "HOOD",   "name": "Robinhood Markets",          "sector": "Finance",         "index": "NASDAQ100"},
    {"ticker": "SOFI",   "name": "SoFi Technologies",          "sector": "Finance",         "index": "NASDAQ100"},
    {"ticker": "AFRM",   "name": "Affirm Holdings",            "sector": "Finance",         "index": "NASDAQ100"},
    {"ticker": "WFC",    "name": "Wells Fargo",                "sector": "Banking",         "index": "SP500"},
    {"ticker": "C",      "name": "Citigroup",                  "sector": "Banking",         "index": "SP500"},
    {"ticker": "USB",    "name": "U.S. Bancorp",               "sector": "Banking",         "index": "SP500"},
    {"ticker": "AXP",    "name": "American Express",           "sector": "Finance",         "index": "SP500"},
    {"ticker": "DIS",    "name": "Walt Disney",                "sector": "Communication",   "index": "SP500"},
    {"ticker": "CMCSA",  "name": "Comcast",                    "sector": "Communication",   "index": "SP500"},
    {"ticker": "T",      "name": "AT&T",                       "sector": "Communication",   "index": "SP500"},
    {"ticker": "VZ",     "name": "Verizon",                    "sector": "Communication",   "index": "SP500"},
    {"ticker": "TMUS",   "name": "T-Mobile US",                "sector": "Communication",   "index": "SP500"},
    {"ticker": "SNAP",   "name": "Snap Inc",                   "sector": "Communication",   "index": "NASDAQ100"},
    {"ticker": "PINS",   "name": "Pinterest",                  "sector": "Communication",   "index": "NASDAQ100"},
    {"ticker": "RBLX",   "name": "Roblox",                     "sector": "Communication",   "index": "NASDAQ100"},
    {"ticker": "LYFT",   "name": "Lyft",                       "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "ABNB",   "name": "Airbnb",                     "sector": "Consumer Disc.",  "index": "NASDAQ100"},
    {"ticker": "BKNG",   "name": "Booking Holdings",           "sector": "Consumer Disc.",  "index": "SP500"},
    {"ticker": "DASH",   "name": "DoorDash",                   "sector": "Consumer Disc.",  "index": "NASDAQ100"},
    {"ticker": "EBAY",   "name": "eBay",                       "sector": "Consumer Disc.",  "index": "SP500"},
    {"ticker": "ETSY",   "name": "Etsy",                       "sector": "Consumer Disc.",  "index": "SP500"},
    {"ticker": "SHOP",   "name": "Shopify",                    "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "WDAY",   "name": "Workday",                    "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "SNOW",   "name": "Snowflake",                  "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "PLTR",   "name": "Palantir Technologies",      "sector": "Technology",      "index": "SP500"},
    {"ticker": "PATH",   "name": "UiPath",                     "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "MDB",    "name": "MongoDB",                    "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "DDOG",   "name": "Datadog",                    "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "CRWD",   "name": "CrowdStrike",                "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "ZS",     "name": "Zscaler",                    "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "OKTA",   "name": "Okta",                       "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "HUBS",   "name": "HubSpot",                    "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "TTD",    "name": "The Trade Desk",             "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "U",      "name": "Unity Software",             "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "APP",    "name": "AppLovin",                   "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "ARM",    "name": "Arm Holdings",               "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "MSTR",   "name": "MicroStrategy",              "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "SMCI",   "name": "Super Micro Computer",       "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "HPQ",    "name": "HP Inc",                     "sector": "Technology",      "index": "SP500"},
    {"ticker": "DELL",   "name": "Dell Technologies",          "sector": "Technology",      "index": "SP500"},
    {"ticker": "HPE",    "name": "Hewlett Packard Enterprise", "sector": "Technology",      "index": "SP500"},
    {"ticker": "CSCO",   "name": "Cisco Systems",              "sector": "Technology",      "index": "SP500"},
    {"ticker": "MU",     "name": "Micron Technology",          "sector": "Technology",      "index": "SP500"},
    {"ticker": "LRCX",   "name": "Lam Research",               "sector": "Technology",      "index": "SP500"},
    {"ticker": "KLAC",   "name": "KLA Corporation",            "sector": "Technology",      "index": "SP500"},
    {"ticker": "AMAT",   "name": "Applied Materials",          "sector": "Technology",      "index": "SP500"},
    {"ticker": "ASML",   "name": "ASML Holding",               "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "TSM",    "name": "Taiwan Semiconductor",       "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "SONY",   "name": "Sony Group",                 "sector": "Technology",      "index": "NASDAQ100"},
    {"ticker": "TM",     "name": "Toyota Motor",               "sector": "Auto",            "index": "NYSE"},
    {"ticker": "HMC",    "name": "Honda Motor",                "sector": "Auto",            "index": "NYSE"},
    {"ticker": "F",      "name": "Ford Motor",                 "sector": "Auto",            "index": "SP500"},
    {"ticker": "GM",     "name": "General Motors",             "sector": "Auto",            "index": "SP500"},
    {"ticker": "RIVN",   "name": "Rivian Automotive",          "sector": "Auto",            "index": "NASDAQ100"},
    {"ticker": "LCID",   "name": "Lucid Group",                "sector": "Auto",            "index": "NASDAQ100"},
    {"ticker": "NIO",    "name": "NIO Inc",                    "sector": "Auto",            "index": "NASDAQ100"},
    {"ticker": "LI",     "name": "Li Auto",                    "sector": "Auto",            "index": "NASDAQ100"},
    {"ticker": "XPEV",   "name": "XPeng",                      "sector": "Auto",            "index": "NASDAQ100"},
    {"ticker": "BYD",    "name": "BYD Co",                     "sector": "Auto",            "index": "NASDAQ100"},
    {"ticker": "CVS",    "name": "CVS Health",                 "sector": "Healthcare",      "index": "SP500"},
    {"ticker": "CI",     "name": "Cigna Group",                "sector": "Healthcare",      "index": "SP500"},
    {"ticker": "HCA",    "name": "HCA Healthcare",             "sector": "Healthcare",      "index": "SP500"},
    {"ticker": "MDT",    "name": "Medtronic",                  "sector": "Healthcare",      "index": "SP500"},
    {"ticker": "ABT",    "name": "Abbott Laboratories",        "sector": "Healthcare",      "index": "SP500"},
    {"ticker": "PFE",    "name": "Pfizer",                     "sector": "Pharma",          "index": "SP500"},
    {"ticker": "BMY",    "name": "Bristol-Myers Squibb",       "sector": "Pharma",          "index": "SP500"},
    {"ticker": "GILD",   "name": "Gilead Sciences",            "sector": "Pharma",          "index": "NASDAQ100"},
    {"ticker": "BIIB",   "name": "Biogen",                     "sector": "Pharma",          "index": "NASDAQ100"},
    {"ticker": "MRNA",   "name": "Moderna",                    "sector": "Pharma",          "index": "NASDAQ100"},
    {"ticker": "REGN",   "name": "Regeneron Pharmaceuticals",  "sector": "Pharma",          "index": "NASDAQ100"},
    {"ticker": "VRTX",   "name": "Vertex Pharmaceuticals",     "sector": "Pharma",          "index": "NASDAQ100"},
    {"ticker": "NKE",    "name": "Nike",                       "sector": "Consumer Disc.",  "index": "SP500"},
    {"ticker": "SBUX",   "name": "Starbucks",                  "sector": "Consumer Disc.",  "index": "SP500"},
    {"ticker": "TGT",    "name": "Target",                     "sector": "Retail",          "index": "SP500"},
    {"ticker": "AMZN",   "name": "Amazon",                     "sector": "Consumer Disc.",  "index": "SP500"},
    {"ticker": "LOW",    "name": "Lowe's",                     "sector": "Retail",          "index": "SP500"},
    {"ticker": "TJX",    "name": "TJX Companies",              "sector": "Retail",          "index": "SP500"},
    {"ticker": "LULU",   "name": "Lululemon Athletica",        "sector": "Consumer Disc.",  "index": "NASDAQ100"},
    {"ticker": "CMG",    "name": "Chipotle Mexican Grill",     "sector": "Consumer Disc.",  "index": "SP500"},
    {"ticker": "YUM",    "name": "Yum! Brands",                "sector": "Consumer Disc.",  "index": "SP500"},
    {"ticker": "CLX",    "name": "Clorox",                     "sector": "FMCG",            "index": "SP500"},
    {"ticker": "CL",     "name": "Colgate-Palmolive",          "sector": "FMCG",            "index": "SP500"},
    {"ticker": "KMB",    "name": "Kimberly-Clark",             "sector": "FMCG",            "index": "SP500"},
    {"ticker": "MO",     "name": "Altria Group",               "sector": "Consumer",        "index": "SP500"},
    {"ticker": "STZ",    "name": "Constellation Brands",       "sector": "Consumer",        "index": "SP500"},
    {"ticker": "BUD",    "name": "Anheuser-Busch InBev",       "sector": "Consumer",        "index": "NYSE"},
    {"ticker": "DAL",    "name": "Delta Air Lines",            "sector": "Industrials",     "index": "SP500"},
    {"ticker": "UAL",    "name": "United Airlines",            "sector": "Industrials",     "index": "NASDAQ100"},
    {"ticker": "AAL",    "name": "American Airlines",          "sector": "Industrials",     "index": "NASDAQ100"},
    {"ticker": "LUV",    "name": "Southwest Airlines",         "sector": "Industrials",     "index": "SP500"},
    {"ticker": "BA",     "name": "Boeing",                     "sector": "Industrials",     "index": "SP500"},
    {"ticker": "LMT",    "name": "Lockheed Martin",            "sector": "Defense",         "index": "SP500"},
    {"ticker": "NOC",    "name": "Northrop Grumman",           "sector": "Defense",         "index": "SP500"},
    {"ticker": "GD",     "name": "General Dynamics",           "sector": "Defense",         "index": "SP500"},
    {"ticker": "DE",     "name": "Deere & Company",            "sector": "Industrials",     "index": "SP500"},
    {"ticker": "UPS",    "name": "United Parcel Service",      "sector": "Industrials",     "index": "SP500"},
    {"ticker": "FDX",    "name": "FedEx",                      "sector": "Industrials",     "index": "SP500"},
]

# ── Helpers ───────────────────────────────────────────────────────────────────
INDIA_STOCKS = NIFTY_50 + NIFTY_NEXT_50 + INDIA_EXTRA
ALL_STOCKS = INDIA_STOCKS + US_TOP_50 + US_EXTRA

INDIA_TICKERS = [s["ticker"] for s in INDIA_STOCKS]
US_TICKERS    = [s["ticker"] for s in US_TOP_50 + US_EXTRA]
ALL_TICKERS   = INDIA_TICKERS + US_TICKERS

TICKER_MAP: dict[str, dict] = {s["ticker"]: s for s in ALL_STOCKS}

def get_market(ticker: str) -> str:
    """Return 'IN' or 'US' for a given ticker."""
    if ticker in US_TICKERS:
        return "US"
    return "IN"


def get_currency(ticker: str) -> str:
    """Return 'INR' or 'USD' for a given ticker."""
    return "USD" if get_market(ticker) == "US" else "INR"
